version: '2'
services:
  backend:
    image: parsley-backend:latest
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - 'NODE_ENV=production'
      - 'DB_URL=db'
    ports:
      - 1337:1337
    links:
      - db
  frontend:
    image: parsley-frontend:latest
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      - 'NODE_ENV=production'
    ports:
      - 3000:3000
  db:
    restart: always
    build:
      context: db
      dockerfile: 'Dockerfile'
    ports:
      - '27017:27017'

