version: '2'
services:
  elasticsearch:
    build:
      context: elastic
      dockerfile: Dockerfile
    ports:
      - 9200:9200
  frontend:
    image: parsley-frontend:latest
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      - 'NODE_ENV=production'
    ports:
      - 3000:3000
  seed:
    build:
      context: seed
      dockerfile: 'Dockerfile'
    ports:
      - '27017:27017'
    links:
     - elasticsearch
    depends_on:
     - elasticsearch
    environment:
     - 'ELASTICSEARCHURL=elasticsearch:9200'
